config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:show] do
    member do
      get :unsave_organisation
    end
  end
  resources :user_organisations, only: [:index, :destroy]
  resources :organisations, only: [:index, :create, :new, :show] do
    member do
      get :save_organisation
      get :unsave_organisation
    end
  end
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :email, format: { with: /\A[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\z/ }
  has_one_attached :photo
  has_many :tags
  has_many :search_words, through: :tags
  has_many :organisation_categories
  has_many :categories, through: :organisation_categories
  has_many :user_organisations
  has_many :users, through: :user_organisations
  accepts_nested_attributes_for :categories
  geocoded_by :full_address
  after_validation :geocode

  include Searchable

  scope :english_speaking, -> { where(english: true) }
  scope :with_volunteering_opportunities, -> { where(volunteering: true) }
  scope :with_internship_opportunities, -> { where(internship: true) }

  #pagination
  self.per_page = 12

  #filters
  def self.filter_by_category(params)
    big_array = params.map do |cat|
      Organisation.joins(categories: [:organisation_categories]).where(organisation_categories:{category_id: cat}).uniq
    end
    flat_big_array = big_array.flatten
    id_array = flat_big_array.map do |e|
      e.id
    end
    amount_of_categories = params.count
    if amount_of_categories > 1
      match_array = id_array.find_all{|e| id_array.count(e) == amount_of_categories}.uniq
      self.where(id: match_array)
    else
      self.where(id: id_array)
    end
  end
    def self.filter_by_size(size)
      self.where(size: size)
    end
  # geocoding

  def full_address
    [street,city,country].compact.join(",")
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  def index
    # no search
    if params[:query].nil?

      if params[:size].nil? && params[:volunteering].nil? && params[:category_id].nil? && params[:english].nil? && params[:internship].nil?
        @organisations = Organisation.page(params[:page]).order(:name)
        #if there is one criteria
      elsif params[:size].present? && params[:volunteering].nil? && params[:category_id].nil? && params[:english].nil? && params[:internship].nil?
        @organisations = Organisation.filter_by_size(params[:size]).page(params[:page])
      elsif params[:volunteering].present? && params[:size].nil? && params[:category_id].nil? && params[:english].nil? && params[:internship].nil?
          @organisations = Organisation.with_volunteering_opportunities.page(params[:page])
      elsif params[:category_id].present? &&  params[:size].nil? && params[:volunteering].nil? && params[:english].nil? && params[:internship].nil?
        @organisations = Organisation.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:english].present? && params[:size].nil? && params[:volunteering].nil? && params[:category_id].nil? && params[:internship].nil?
        @organisations = Organisation.english_speaking.page(params[:page])
      elsif params[:internship].present? && params[:size].nil? && params[:volunteering].nil? && params[:category_id].nil? && params[:english].nil?
        @organisations = Organisation.with_internship_opportunities.page(params[:page])
        #if there is 2 filters
      elsif params[:category_id].present? && params[:english].present? && params[:size].nil? && params[:volunteering].nil? && params[:internship].nil?
        @organisations = Organisation.english_speaking.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:size].present? && params[:volunteering].nil? && params[:english].nil? && params[:internship].nil?
        @organisations = Organisation.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].nil? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.with_volunteering_opportunities.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].nil? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].present? && params[:volunteering].nil? && params[:internship].nil?
        @organisations = Organisation.english_speaking.filter_by_size(params[:size]).page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].nil? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.english_speaking.with_volunteering_opportunities.page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].nil? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_internship_opportunities.page(params[:page])
      elsif params[:category_id].nil? && params[:english].nil? && params[:size].present? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.filter_by_size(params[:size]).with_volunteering_opportunities.page(params[:page])
      elsif params[:category_id].nil? && params[:english].nil? && params[:size].present? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.filter_by_size(params[:size]).with_internship_opportunities.page(params[:page])
      elsif params[:category_id].nil? && params[:english].nil? && params[:size].nil? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.with_volunteering_opportunities.with_internship_opportunities.page(params[:page])
        #if there is 3 filters
      elsif params[:category_id].present? && params[:english].present? && params[:size].present? && params[:volunteering].nil? && params[:internship].nil?
        @organisations = Organisation.english_speaking.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].present? && params[:size].nil? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.english_speaking.with_volunteering_opportunities.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].present? && params[:size].nil? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_internship_opportunities.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].present? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.with_volunteering_opportunities.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].present? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].nil? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.with_volunteering_opportunities.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].present? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.english_speaking.with_volunteering_opportunities.filter_by_size(params[:size]).page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].present? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_internship_opportunities.filter_by_size(params[:size]).page(params[:page])
      elsif params[:category_id].nil? && params[:english].present? && params[:size].nil? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_internship_opportunities.with_volunteering_opportunities.page(params[:page])
      elsif params[:category_id].nil? && params[:english].nil? && params[:size].present? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.with_volunteering_opportunities.filter_by_size(params[:size]).page(params[:page])
        #if there is 4 filters
      elsif params[:category_id].nil? && params[:english].present? && params[:size].present? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_internship_opportunities.with_volunteering_opportunities.filter_by_size(params[:size]).page(params[:page])
      elsif params[:category_id].present? && params[:english].nil? && params[:size].present? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.with_volunteering_opportunities.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].present? && params[:size].nil? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.with_volunteering_opportunities.english_speaking.filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].present? && params[:size].present? && params[:volunteering].nil? && params[:internship].present?
        @organisations = Organisation.with_internship_opportunities.english_speaking.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
      elsif params[:category_id].present? && params[:english].present? && params[:size].present? && params[:volunteering].present? && params[:internship].nil?
        @organisations = Organisation.with_volunteering_opportunities.english_speaking.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
        #if is 5 filters
      elsif params[:category_id].present? && params[:english].present? && params[:size].present? && params[:volunteering].present? && params[:internship].present?
        @organisations = Organisation.english_speaking.with_volunteering_opportunities.english_speaking.filter_by_size(params[:size]).filter_by_category(params[:category_id]).page(params[:page])
     end

    else
      #when the index is accessed through search bar
      response = Organisation.search(params[:query])
      unless response.results.first.nil?
        @organisations = response.records.to_a
      end

    end

    filter_bar(params)
    @categories = Category.all
    @main_categories = Category.main
    @other_categories = Category.other
  end

  def show
    @organisation = Organisation.find(params[:id])
  end
  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)

app/helpers/organisations_helper.rb
module OrganisationsHelper

  def format_url(url)
    if url.nil?
      return url
    else
      shorter_url = url.split('//')[1]
      unless shorter_url.nil?
      pretty_url = shorter_url.slice(0...shorter_url.index('/'))
      return pretty_url
      else
      url.slice(0...url.index('/'))
      end
    end
  end
end

app/views/organisations/_organisation.html.erb
<% unless organisation.nil? %>
  <div data-controller="expandorg">
    <%# card start %>
    <div class="org-card" data-expandorg-target="expandorgbtn" data-action="click->expandorg#showOrganisation">
    <%# if I am in user %>
      <% if controller_name == "users" %>
        <% if current_user.organisations.include?(organisation) %>
          <%= link_to unsave_organisation_user_path(current_user, organisation: organisation), method: :delete, remote: true , class: "unsave-org-btn" do %>
            <div class="unsave-org-btn-icon dont-open-preview-btn"></div>
          <% end %>
        <% end %>
      <% else %>
       <%# if i am in organisation index %>
        <% if current_user %>
          <turbo-frame id="organisation-card">
            <% if current_user.organisations.include?(organisation) %>
              <%= link_to unsave_organisation_organisation_path(organisation, user: current_user), method: :delete, remote: true , class: "save-org-btn dont-open-preview-btn" do %>
                <div class="save-org-btn-icon clicked dont-open-preview-btn"></div>
              <% end %>
            <% else %>
              <%= link_to save_organisation_organisation_path(organisation, user: current_user), method: :post, remote: true, class: "save-org-btn dont-open-preview-btn"  do %>
                <div class="save-org-btn-icon dont-open-preview-btn"></div>
              <% end %>
            <% end %>
          </turbo-frame>
        <% else %>
          <%= link_to new_user_session_path, class: "save-org-btn"  do %>
            <%= image_tag "icons/star_line_green_icon.svg", alt: "star icon empty" , class: "save-org-btn-icon dont-open-preview-btn"%>
          <% end %>
        <% end %>
      <% end %>
      <%# org logo section %>
      <div class="org-card-logo">
        <% unless organisation.photo.key.nil? %>
          <div class="logo-frame">
            <%= cl_image_tag organisation.photo.key, height: 150, width:150, crop: :fit, class: "org-logo" %>
          </div>
        <% end %>
      </div>
      <%# end of org logo section %>
      <%# org card title and subtitle section %>
      <div class="org-card-text">
        <div class="org-card-info" data-name="<%= organisation.name %>">
          <h3><%= organisation.name.upcase %></h3>
          <h4><%= organisation.subheading %></h4>
        </div>
                      <%# <div class="org-card-foot" data-expandorg-target="expandOrgBtn" data-action="click->expandorg#showOrganisation">
                        <%= image_tag "icons/expand_org_icon.svg", alt: "expand organisation icon", class: "expand-org-btn" %>
                     <%#  </div> %>
      </div>
    </div>
                  <%# card-div-end %>
                  <%# org preview  %>
                    <div class="org-preview" data-expandorg-target="orgpreview" hidden>
                      <div class="org-preview-card">
                        <div class="preview-top">
                          <div class="close-btn" data-action="click->expandorg#showOrganisation" data-expandorg-targets="closepreviewbtn">
                            <%= image_tag "icons/close_icon.svg", alt: "close icon", class: "close-btn-icon"%>
                          </div>
                        </div>
                        <div class="preview-content">
                          <div class="logo">
                            <% unless organisation.photo.key.nil? %>
                              <%= cl_image_tag organisation.photo.key, class: "logo-show"%>
                            <% end %>
                          </div>
                          <div class="preview-head">
                            <h3><%= organisation.name.upcase %></h3>
                            <h4><%= organisation.subheading %></h4>
                          </div>
                          <div class="characteristics">
                            <% unless organisation.size.nil? %>
                              <div class="characteristics-item">
                                <%= image_tag "icons/orgsize_icon.svg"%>
                                <h5><%=organisation.size.capitalize %> organization</h5>
                              </div>
                            <% end %>
                            <% unless organisation.volunteering.nil? %>
                               <div class="characteristics-item">
                                <%= image_tag "icons/volunteering_icon.svg"%>
                                <h5>Volunteering opportunities</h5>
                              </div>
                            <% end %>
                            <% unless organisation.internship.nil? %>
                              <div class="characteristics-item">
                                <%= image_tag "icons/internship_icon.svg"%>
                                <h5>Internship programme</h5>
                              </div>
                            <% end %>
                            <% unless organisation.unsolicited.nil? %>
                              <div class="characteristics-item">
                                <%= image_tag "icons/unsolicited_icon.svg"%>
                                <h5>Open to unsolicited applications</h5>
                              </div>
                            <% end %>
                            <% unless organisation.english.nil? %>
                              <div class="characteristics-item">
                                <%= image_tag "icons/english_icon.svg"%>
                                <h5>English speaking opportunities</h5>
                              </div>
                            <% end %>
                          </div>
                          <div class="preview-body">
                            <p><%= organisation.description %></p>
                          </div>
                          <div class="map">map</div>
                          <div class="preview-foot">
                            <div class="contact">
                              <h3>Contact</h3>
                              <a href="<%= organisation.website%>" target="_blank"><p><%= format_url(organisation.website)%></p></a>
                              <p><%= organisation.email%></p>
                              <h5>Address</h5>
                              <p><%= organisation.street %></p>
                              <p><%= organisation.city %></p>
                              <p><%= organisation.zip %></p>
                              <p><%= organisation.country %></p>
                            </div>
                            <div class="some-links">
                              <%= link_to organisation.facebook, target: :_blank  do %>
                                <%= image_tag "icons/fb_icon.svg" %>
                              <% end %>
                              <%= link_to organisation.linkedin, target: :_blank do %>
                                <%= image_tag "icons/linkedin_icon.svg" %>
                              <% end %>
                            </div>
                            <%= link_to "More", organisation_path(organisation) %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
          <% end %>

app/views/organisations/index.html.erb
<div class="container">
  <div class="filter-bar ">
    <div class="filter-left">
      <%= image_tag "icons/filter_icon.svg" %>
      <% unless @filters.nil? %>
      <% @filters.each do |filter| %>
      <div class="filter-selected">
       <%= filter.upcase %>
      </div>
      <% end %>
      <% end %>
    </div>
    <div class="filter-right">
      <%= image_tag "icons/sort_icon.svg", id:"sort-icon" %>
    </div>
  </div>
  <div class="content-container">
  <div data-controller="sidebar" class="open-side-bar-container">
    <div data-sidebar-target="openSidebarBtn" data-action="click->sidebar#openSidebar" class="open-side-bar-btn">Filters</div>
    <%# start sidebar %>
    <div class="side-bar" data-sidebar-target="sidebar">
      <% if params[:applied_filter].present? %>
        <%= link_to "Show all", organisations_path %>
      <% end %>
      <h1>Filter bar</h1>
      <%= form_with url: organisations_path, method: :get, id:"filter-form" do  %>
      <h5>Main categories</h5>
      <div class="form-group categories-main">
        <%= fields_for @category do |c| %>
          <% @main_categories.each do |category| %>
            <%= c.check_box :category_id, {:multiple => true, id: category.name }, category.id, false %>
            <%= c.label category.name, category.name.upcase %>
          <% end %>
        <% end %>
      </div>
      <div data-controller="visibility">
        <div class="filter-control" data-action="click->visibility#showTargets" data-visibility-target="showBtn"><%= image_tag "icons/plus_icon.svg" %> Expand selection </div>
        <div class="filter-control" data-action="click->visibility#hideTargets" data-visibility-target="hideBtn" hidden><%= image_tag "icons/minus_icon.svg" %> Minimize selection</div>
        <div class="expand-box" data-visibility-target="hideable" hidden>
        <%# hidden filters %>
        <h5>Other categories</h5>
          <div class="form-group other-categories">
              <%= fields_for @category do |c|%>
                <% @other_categories.each do |category| %>
                    <%= c.check_box :category_id, {:multiple => true, id: category.name }, category.id, false %>
                    <%= c.label category.name, category.name.capitalize, class:"other-category-label" %>
                <% end %>
              <% end %>
          </div>
            <h5>Organisation size</h5>
          <div class="form-group organisation-size">
            <%= radio_button_tag :size, "small" %>
            <%= label_tag :size_small, "Small" %>
            <%= radio_button_tag :size, "medium" %>
            <%= label_tag :size_medium, "Medium" %>
            <%= radio_button_tag :size, "large" %>
            <%= label_tag :size_large, "Large" %>
          </div>
          <h5>Other</h5>
          <div class="form-group volunteering">
            <%= check_box_tag :volunteering, "true" %>
            <%= label_tag :volunteering, "Volunteer opportunities" %>
          </div>
          <div class="form-group internship">
            <%= check_box_tag :internship, "true" %>
            <%= label_tag :internship, "Internship opportunities" %>
          </div>
        </div>
        <%# end of hidden filters %>
      </div>
      <div class="form-group english">
        <%= check_box_tag :english, "true" %>
        <%= label_tag :english, "ENGLISH" %>
      </div>
      <%= hidden_field_tag "applied_filter", :true %>
        <%= button_tag :submit, class:"filter-btn" do%>
            <%= image_tag "icons/filter_white_icon.svg" %>
            <p>Apply filters</p>
        <% end %>
      <% end %>
    </div>
    <%# sidebar end %>
   </div>
    <div class="main-content">
      <% unless @organisations.nil? || @organisations == [] %>
        <div class="org-grid">
            <%= render @organisations %>
        </div>
            <%= will_paginate @organisations %>
      <% end %>
    </div>
  </div>
  <%= link_to "Create new organisation", new_organisation_path %>
</div>

app/views/organisations/new.html.erb
<%= form_with model: @organisation do |f|%>
  <div class="form-section">
    <h3>Main info</h3>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :subheading %>
    <%= f.text_field :subheading %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :size, "Organisation size" %>
    <%= f.select :size, ["small","medium","large"] %>
  </div>
  <div class="form-section">
    <h3>Contact details</h3>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <%= f.file_field :photo %>
  <%= f.label :volunteering, "Volunteering opportunities" %>
  <%= f.check_box :volunteering %>
    <div class="form-section">
      <h3>Tags</h3>
      <%= f.fields_for :search_words do |t|%>
      <%= t.collection_check_boxes :search_word, SearchWord.all, :search_word, :search_word do |b|%>
      <%= b.label %>
      <%= b.check_box  %>
      <% end %>
      <% end %>
    </div>
    <div class="form-section">
      <h3>Categories</h3>
      <%= fields_for :categories do |c|%>
        <%= c.collection_check_boxes :name, Category.all, :name, :name do |b|%>
          <%= b.label  %>
          <%= b.check_box %>
        <% end %>
      <% end %>
    </div>
    <div class="form-section">
      <h3>Address</h3>
      <%= f.label :street, "Street" %>
      <%= f.text_field :street %>
      <%= f.label :zip, "ZIP" %>
      <%= f.text_field :zip   %>
      <%= f.label :city, "City" %>
      <%= f.text_field :city %>
      <%= f.label :country, "Country" %>
      <%= f.text_field :country  %>
    </div>
 <%# will add nested fields_for with checkboxes and add new tag thingy %>
  <%= f.submit "Create organisation" %>
<% end %>

app/views/organisations/show.html.erb
<%= @organisation.latitude %>
<%= @organisation.longitude %>