config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:show] do
    member do
      get :unsave_organisation
    end
  end
  resources :user_organisations, only: [:index, :destroy]
  resources :organisations, only: [:index, :create, :new, :show] do
    member do
      get :save_organisation
      get :unsave_organisation
    end
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="mobile-view-nav">
    <%= link_to "ImpactArc", root_path, class:"nav-link-text nav-logo" %>
    <div data-controller="dropdown">
      <%= image_tag "icons/user_full_purple_icon.svg",alt: "user icon", class: "user-icon", data: {dropdown_target: "showDropdownBtn", action: "click->dropdown#toggleDropdown"} %>
      <div class="dropdown-nav mobile-view-dropdown" data-dropdown-target="dropdownList">
        <%= link_to "Organizations", organisations_path %>
        <% if current_user %>
        <%= link_to "My dashboard", user_path(current_user)%>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete , class: "classic-link"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="nav-left">
    <%= link_to "ImpactArc", root_path, class:"nav-link-text nav-logo" %>
    <%= link_to "Project", root_path, class:"nav-link-text" %>
    <%= link_to "Organisations", organisations_path, class: "nav-link-text" %>
  </div>
  <div class="nav-right">
    <div data-controller="searchbar" class="search">
      <%= form_with url: organisations_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "search-bar", data: {searchbar_target: "searchBar"} %>
        <%= hidden_field_tag "applied_filter", :true %>
        <%= submit_tag "Search", style: "display: none" %>
      <% end %>
      <%= image_tag "icons/search_icon.svg", data: {action:"click->searchbar#animateSearchBar"}, class:"search-icon" %>
    </div>
    <% if user_signed_in? %>
    <div data-controller="dropdown">
      <%= image_tag "icons/user_full_purple_icon.svg",alt: "user icon", class: "user-icon", data: {dropdown_target: "showDropdownBtn", action: "click->dropdown#toggleDropdown"} %>
      <div class="dropdown-nav" data-dropdown-target="dropdownList">
        <%= link_to "My dashboard", user_path(current_user)%>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete , class: "classic-link"%>
      </div>
    </div>
    <% else %>
    <%= link_to new_user_session_path do %>
    <button class="log-in normal-btn">Log in</button>
    <% end %>
    <% end %>
  </div>
</div>